### ISSUE TITLE
Copywriting proposal.

### ISSUE THREAD

**Issue by HarryHeights** [hapramp/Hapramp-Android#61]
Hello, I'm Harry. 
I got hint of your app when I saw it was listed in utopian bug hunting whitelist.  
I'm a copywriter though and I could contribute to your project in the area. I see Hapramp doesn't yet have FAQs for the newly launched app and the FAQs on the website aren't enough to assist new users. I also saw that there's no privacy policy. 
I could create these documents if you want them.

I'll be expecting a reply thanks.

**Comment by aviaryan** [comment]
We are already working on the privacy policy. Can you work on the FAQs?
You can send a PR.

**Comment by HarryHeights** [comment]
I'll do it right away

**Comment by HarryHeights** [comment]
Hello, is there a way I can communicate with you other than Github? I'll need some more technical details.

**Comment by raj-at** [comment]
Hello, you may join our Discord by clicking on this link: https://discord.gg/PkgCv8j
We'll collaborate to add more FAQs to the website. We'll soon add 'Help' in the Android app too.

**Comment by HarryHeights** [comment]
Good thanks.
