### ISSUE TITLE
Posts are not getting displayed in Profile tab

### ISSUE THREAD

**Issue by ng-gist** [hapramp/Hapramp-Android#62]
#### Expected behavior

My posts should always be displayed when i go to Profile page

#### Actual behavior

Profile page doesn't show my posts initially but after visiting create blog and returning, i can see my posts.

#### How to reproduce

1. Open the app.
2. Go to Profile my clicking on the profile link on the bottom of the screen.
3. Try to scroll posts in the view area.
Addition steps to see the posts.
4. Click on Create and then blog.
5. Exit out of create blog to go back to posts page.
6. Now you can scroll the post in view area.

#### Profile User for testing:
https://steemit.com/@fastandcurious

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/13856451/43997204-8c1036ac-9d8a-11e8-9738-6b956bc902d2.gif)

* Device : Samsung S8
* System Operating : 8.0.0 Oreo
* App Version: 0.0.7

**Comment by mightypanda-x** [comment]
I think i spoke too soon. I can see that issue again.

**Comment by singhpratyush** [comment]
@bxute: Any idea why this is happening again?
