### ISSUE TITLE
Hapramp fails to validate

### ISSUE THREAD

**Issue by jubreal** [hapramp/Hapramp-Android#72]
#### Expected behavior
Users should be able to log in to use the app through steemconnect after providing correct steemit username and password 

#### Actual behavior

Verification failed after providing correct user info to log in. 
 

#### How to reproduce
- Download the latest app version
- Log in by providing the correct steemit username and password.

It would be observed that the validation fails after loading.

* Browser/App version: Hapramp version 0.0.7
* Operating system: Android version 6.0

#### Recording Of The Bug

https://youtu.be/_2_pWgGswcE

**Comment by josephace135** [comment]
I experience the same too

**Comment by aviaryan** [comment]
Can you please try this release? https://github.com/hapramp/Hapramp-Android/releases/tag/v0.0.8
Thanks

**Comment by aviaryan** [comment]
If experiencing a problem, uninstall the app and install it again from the link above. I believe the issue is solved.

**Comment by jubreal** [comment]
Yes.  The issue is solved with the updates. I'm already testing the new
update. Thanks
