### ISSUE TITLE
Search user - If the name being searched starts with an uppercase letter, the results are list of the steem user names in alphabetical form

### ISSUE THREAD

**Issue by royachiron** [hapramp/Hapramp-Android#93]
See gif. Or try for yourself - search for your username and start with uppercase letter. I know steem usernames doesn't have uppercase letters (tho the full name does have upper and lowercase) but it is usually the default first letter in most mobile keyboards, so it might just not be that obvious to all users.

![72](https://user-images.githubusercontent.com/23020420/44124991-c2a7a28a-a038-11e8-97fa-92c523cc5a91.gif)

**Comment by singhpratyush** [comment]
Thanks for reporting @royachiron. We'll look into the issue.
