### ISSUE TITLE
Saving Profile edits redirects to browser

### ISSUE THREAD

**Issue by aashutoshrathi** [hapramp/Hapramp-Android#94]
When profile changes are made and saved, they should be saved in app, instead it redirects to Steem Transaction confirmation page and then save it.

_Sent from my Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by singhpratyush** [comment]
Yes. The profile changes need to be made using [SteemConnect](https://steemconnect.com) on a browser.
