### ISSUE TITLE
[Suggestion] Username on wallet should be clickable and redirect to that user's profile

### ISSUE THREAD

**Issue by sourovafrin** [hapramp/Hapramp-Android#95]
![screenshot_20180814-111413](https://user-images.githubusercontent.com/38147368/44138098-a2844f06-a094-11e8-9355-c5d2053a66de.jpg)

Username on wallet should be clickable and clicking on it should take us on user's profile..

![screenshot_20180815-021207](https://user-images.githubusercontent.com/38147368/44138127-c0f41494-a094-11e8-81ce-07833895d83e.jpg)

Clicking on followers should show all followers list. And beside of the username there will be a follow button to follow my followers and unfollow button whom i already following. 
same for following with unfollow button beside of the username.

**Comment by singhpratyush** [comment]
Renaming as a part of it is mentioned in #56.
