### ISSUE TITLE
[Version 0.0.10] - "Edit Community" button appears in the "Interests" of a user being visited

### ISSUE THREAD

**Issue by josephace135** [hapramp/Hapramp-Android#97]
#### Expected behavior
When visiting a user that is registered to HapRamp, one should only be able to see the “Communities” being selected by that user as his “Interests”.

#### Actual behavior
Upon visiting a user that is registered to HapRamp, the “Interests” of that user is displayed and at the same time, the “Edit Community” button which can be tapped. The appearance of that button is a bit strange since one might think that they can edit other user’s “Interests”. (Fortunately, when a user taps the “Edit Community” button it loads the communities and when a user adds/removes a community, the changes apply to the visiting user’s account.)
	
#### How to reproduce
* Download the latest release of HapRamp-Android from [GitHub](https://github.com/hapramp/Hapramp-Android/releases).
* Open the HapRamp app.
* Log-in via SteemConnect using your Steemit username and password.
* After a successful log-in, tap the icon for “Search”.
* Input the username of that user you intend to visit. (Important note: The user that you intend to visit must be registered to HapRamp to be able to see his/her “Interests”.)
* The search results would appear and tap the username of that user you intend to visit.
* When the profile of the user you’ve visited finishes loading, scroll down and you’ll see “Edit Community” button which is found next to the communities being listed on user’s “Interests”.
.

#### Environment
* App/Plugin version: HapRamp-Android v0.0.10
* Device: Samsung Galaxy J2 Prime (SM-G532G/DS)
* Operating system: Android version 6.0.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=rLbu7LqSsig

**Comment by singhpratyush** [comment]
That's a critical one - thanks for reporting @josephace135.
